enableImmutableInstalls: false
enableScripts: false
enableTelemetry: false
enableGlobalCache: false
logFilters:
  - code: YN0000
    level: disallowed
    text: |
      ⚠️ This project is configured to use Bun, not Yarn. Please use 'bun' for package management. ⚠️
      To install dependencies, run 'bun install' instead.