services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: sh -c "apt-get update && apt-get install -y procps && bun run dev"
    restart: always
    depends_on:
      - mongodb
    env_file:
      - ./.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app

  mongodb:
    image: mongo:7.0-jammy
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bs
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '0.0.0.0:27017:27017'
    volumes:
      - mongodb_datadir:/data/db
    restart: always

  fmcd:
    image: okjodom/fmcd:latest
    container_name: fmcd
    environment:
      - FMCD_DATA_DIR=/data
      - FMCD_ADDR=0.0.0.0:7070
      - FMCD_MODE=rest
      - FMCD_INVITE_CODE=fed11qgqrgvnhwden5te0v9k8q6rp9ekh2arfdeukuet595cr2ttpd3jhq6rzve6zuer9wchxvetyd938gcewvdhk6tcqqysptkuvknc7erjgf4em3zfh90kffqf9srujn6q53d6r056e4apze5cw27h75
      # Option A: Auto-generate password (default)
      # Option B: Set explicit password
      # - FMCD_PASSWORD=fmcdpass
      # Option C: Disable auth (dev only)
      # - FMCD_NO_AUTH=true
    ports:
      - 7070:7070
    volumes:
      - fmcd_datadir:/data
    restart: always

volumes:
  mongodb_datadir:
  fmcd_datadir:
