services:
  admin:
    container_name: admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      target: development
    command: sh -c "cd /app/apps/admin && bun run dev"
    restart: always
    depends_on:
      - server
    env_file:
      - ./apps/admin/.dev.env
    ports:
      - '3000:3000'
    volumes:
      - .:/app

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      target: development
    command: bun dev server
    restart: always
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./apps/server/.dev.env
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app

  swap:
    container_name: swap
    build:
      context: .
      dockerfile: ./apps/swap/Dockerfile
      target: development
    command: [
        "sh",
        "-c",
        "bun dev swap"
      ]
    restart: always
    depends_on:
      - clientd
      - mongodb
      - redis
    env_file:
      - ./apps/swap/.dev.env
    ports:
      - '4040:4040'
      - '4042:4042'
    volumes:
      - .:/usr/src/app

  mongodb:
    image: mongo:7.0-jammy
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bs
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '0.0.0.0:27017:27017'
    volumes:
      - mongodb_datadir:/data/db
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    command: [
      "sh", "-c", 
      "redis-server --requirepass ${REDIS_PASSWORD:-securepassword} --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes"
    ]
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-securepassword}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  clientd:
    image: okjodom/fedimint-clientd:v0.4.1
    container_name: clientd
    environment:
      - FEDIMINT_CLIENTD_DB_PATH=/var/lib/clientd
      - FEDIMINT_CLIENTD_PASSWORD=fmcdpass
      - FEDIMINT_CLIENTD_ADDR=clientd:7070
      - FEDIMINT_CLIENTD_MODE=rest
      # - FEDIMINT_CLIENTD_INVITE_CODE=fed11qgqrwdthwden5te0v9cxjttndakk2ttrdpjk2um994erx7rsx568vur9dy68z6pnvd6xg63hwsh8wmn90p6zuctswqhsqqfqt94ttf29vdm0jfw3gk3w7quvcknshxd705ksavc0ajj7sj0v6dgsxcydnc
      - FEDIMINT_CLIENTD_INVITE_CODE=fed11qgqrsdnhwden5te0dp6k6mtfdenj6mr0v3nk2tfk09jkkeekxechqmphdvm8wdttxauxvufwwahx27r59eshqup0waej7qqpyq8kqe90ktshlvw3f88ztywxz559ag0yjvljvvtd3kepx2sfg2qdjn7s5m0
    ports:
      - 7070:7070
    volumes:
      - clientd_datadir:/var/lib/clientd
    restart: always

volumes:
  mongodb_datadir:
  clientd_datadir:
  redis_data:
