services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: sh -c "apt-get update && apt-get install -y procps && bun run dev"
    restart: always
    depends_on:
      - mongodb
    env_file:
      - ./.dev.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app

  mongodb:
    image: mongo:7.0-jammy
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bs
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '0.0.0.0:27017:27017'
    volumes:
      - mongodb_datadir:/data/db
    restart: always

  clientd:
    image: okjodom/fedimint-clientd:v0.4.1
    container_name: clientd
    environment:
      - FEDIMINT_CLIENTD_DB_PATH=/var/lib/clientd
      - FEDIMINT_CLIENTD_PASSWORD=fmcdpass
      - FEDIMINT_CLIENTD_ADDR=clientd:7070
      - FEDIMINT_CLIENTD_MODE=rest
      - FEDIMINT_CLIENTD_INVITE_CODE=fed11qgqrgvnhwden5te0v9k8q6rp9ekh2arfdeukuet595cr2ttpd3jhq6rzve6zuer9wchxvetyd938gcewvdhk6tcqqysptkuvknc7erjgf4em3zfh90kffqf9srujn6q53d6r056e4apze5cw27h75
    ports:
      - 7070:7070
    volumes:
      - clientd_datadir:/var/lib/clientd
    restart: always

volumes:
  mongodb_datadir:
  clientd_datadir:
