global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing endpoints to scrape
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # API Gateway (federates metrics from all services)
  - job_name: "api"
    scrape_interval: 10s
    metrics_path: /v1/metrics
    static_configs:
      - targets: ["api:4000"]

  # Individual service metrics endpoints
  - job_name: "auth"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["auth:4012"]
      
  - job_name: "nostr"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["nostr:4052"]
      
  - job_name: "sms"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["sms:4062"]
      
  - job_name: "shares"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["shares:4072"]
    
  - job_name: "solowallet"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["solowallet:4082"]
    
  - job_name: "chama"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["chama:4092"]
    
  - job_name: "swap"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["swap:4042"]

  - job_name: "notification"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["notification:5002"]
