import { PermissionCategory } from '../database/permission.schema';

/**
 * All system permissions
 * Based on the Permission System Design Document
 */
export const PERMISSIONS = [
  // ===== USER PERMISSIONS (18) =====
  {
    permission: 'user:read:own',
    description: 'Read own user profile',
    category: PermissionCategory.User,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'user:read:any',
    description: 'Read any user profile (admin)',
    category: PermissionCategory.User,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'user:search',
    description: 'Search for users',
    category: PermissionCategory.User,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'user:create',
    description: 'Create new user account',
    category: PermissionCategory.User,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'user:update:own',
    description: 'Update own user profile',
    category: PermissionCategory.User,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'user:update:any',
    description: 'Update any user profile (admin)',
    category: PermissionCategory.User,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'user:delete:own',
    description: 'Delete own user account',
    category: PermissionCategory.User,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'user:delete:any',
    description: 'Delete any user account (super admin)',
    category: PermissionCategory.User,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'user:roles:read:own',
    description: 'View own roles',
    category: PermissionCategory.User,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'user:roles:update:any',
    description: 'Modify user roles (admin)',
    category: PermissionCategory.User,
    requiresContext: false,
    isConditional: false,
  },

  // ===== CHAMA PERMISSIONS (26) =====
  {
    permission: 'chama:create',
    description: 'Create new chama',
    category: PermissionCategory.Chama,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'chama:search',
    description: 'Search and discover chamas',
    category: PermissionCategory.Chama,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'chama:list:own',
    description: 'List chamas where user is a member',
    category: PermissionCategory.Chama,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'chama:read:own',
    description: 'Read chamas where user is a member',
    category: PermissionCategory.Chama,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'chama:read:invited',
    description: 'Preview chamas where user has pending invitation',
    category: PermissionCategory.Chama,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'chama:read:any',
    description: 'Read any chama (admin)',
    category: PermissionCategory.Chama,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'chama:update:own',
    description: 'Update chama as member',
    category: PermissionCategory.Chama,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'chama:update:any',
    description: 'Update any chama (admin)',
    category: PermissionCategory.Chama,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'chama:delete:own',
    description: 'Delete own chama',
    category: PermissionCategory.Chama,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'chama:delete:any',
    description: 'Delete any chama (super admin)',
    category: PermissionCategory.Chama,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'chama:member:add',
    description: 'Add members to chama',
    category: PermissionCategory.Chama,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'chama:member:remove',
    description: 'Remove members from chama',
    category: PermissionCategory.Chama,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'chama:member:update_roles',
    description: 'Update member roles in chama',
    category: PermissionCategory.Chama,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'chama:invite:send',
    description: 'Send chama invitations',
    category: PermissionCategory.Chama,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'chama:invite:revoke',
    description: 'Revoke chama invitations',
    category: PermissionCategory.Chama,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'chama:invite:manage',
    description: 'Manage all chama invitations',
    category: PermissionCategory.Chama,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'chama:join:public',
    description: 'Join public chamas',
    category: PermissionCategory.Chama,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'chama:join:invited',
    description: 'Join chamas via invitation',
    category: PermissionCategory.Chama,
    requiresContext: false,
    isConditional: false,
  },

  // ===== WALLET PERMISSIONS (22) =====
  {
    permission: 'wallet:read:own',
    description: 'View own wallet balance',
    category: PermissionCategory.Wallet,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'wallet:read:chama',
    description: 'View chama wallet balance',
    category: PermissionCategory.Wallet,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'wallet:read:any',
    description: 'View any wallet (admin)',
    category: PermissionCategory.Wallet,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'wallet:deposit:own',
    description: 'Deposit to own wallet',
    category: PermissionCategory.Wallet,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'wallet:deposit:chama',
    description: 'Deposit to chama wallet',
    category: PermissionCategory.Wallet,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'wallet:withdraw:own',
    description: 'Withdraw from own wallet',
    category: PermissionCategory.Wallet,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'wallet:withdraw:chama',
    description: 'Withdraw from chama wallet',
    category: PermissionCategory.Wallet,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'wallet:withdraw:approve',
    description: 'Approve withdrawal requests',
    category: PermissionCategory.Wallet,
    requiresContext: true,
    isConditional: false,
  },

  // ===== TRANSACTION PERMISSIONS (14) =====
  {
    permission: 'transaction:create:own',
    description: 'Create transaction from own wallet',
    category: PermissionCategory.Transaction,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'transaction:create:chama',
    description: 'Create chama transaction',
    category: PermissionCategory.Transaction,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'transaction:read:own',
    description: 'Read own transactions',
    category: PermissionCategory.Transaction,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'transaction:read:chama',
    description: 'Read chama transactions',
    category: PermissionCategory.Transaction,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'transaction:read:any',
    description: 'Read any transaction (admin)',
    category: PermissionCategory.Transaction,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'transaction:update:own',
    description: 'Update own pending transactions',
    category: PermissionCategory.Transaction,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'transaction:update:chama',
    description: 'Update chama transactions',
    category: PermissionCategory.Transaction,
    requiresContext: true,
    isConditional: false,
  },
  {
    permission: 'transaction:cancel:own',
    description: 'Cancel own pending transactions',
    category: PermissionCategory.Transaction,
    requiresContext: false,
    isConditional: false,
  },

  // ===== PERSONAL SAVINGS PERMISSIONS (12) =====
  {
    permission: 'personal:wallet:create',
    description: 'Create personal savings wallet',
    category: PermissionCategory.Personal,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'personal:wallet:read:own',
    description: 'Read own personal wallets',
    category: PermissionCategory.Personal,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'personal:wallet:update:own',
    description: 'Update personal wallet settings',
    category: PermissionCategory.Personal,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'personal:wallet:delete:own',
    description: 'Delete personal wallet',
    category: PermissionCategory.Personal,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'personal:target:create',
    description: 'Create savings target',
    category: PermissionCategory.Personal,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'personal:target:update:own',
    description: 'Update savings target',
    category: PermissionCategory.Personal,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'personal:target:complete',
    description: 'Complete or delete savings target',
    category: PermissionCategory.Personal,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'personal:locked:create',
    description: 'Create locked savings',
    category: PermissionCategory.Personal,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'personal:locked:update:own',
    description: 'Update locked wallet',
    category: PermissionCategory.Personal,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'personal:locked:withdraw_early',
    description: 'Withdraw early from locked savings (with penalty)',
    category: PermissionCategory.Personal,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'personal:analytics:read:own',
    description: 'View personal analytics',
    category: PermissionCategory.Personal,
    requiresContext: false,
    isConditional: false,
  },

  // ===== SHARES PERMISSIONS (16) =====
  {
    permission: 'shares:offer:create',
    description: 'Create share offer',
    category: PermissionCategory.Shares,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'shares:offer:read',
    description: 'View share offers',
    category: PermissionCategory.Shares,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'shares:offer:update:own',
    description: 'Update own share offers',
    category: PermissionCategory.Shares,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'shares:offer:cancel:own',
    description: 'Cancel own share offer',
    category: PermissionCategory.Shares,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'shares:subscribe',
    description: 'Subscribe to shares',
    category: PermissionCategory.Shares,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'shares:transfer:own',
    description: 'Transfer own shares',
    category: PermissionCategory.Shares,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'shares:read:own',
    description: 'View own shares',
    category: PermissionCategory.Shares,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'shares:read:any',
    description: 'View all shares (admin)',
    category: PermissionCategory.Shares,
    requiresContext: false,
    isConditional: false,
  },

  // ===== NOTIFICATION PERMISSIONS (12) =====
  {
    permission: 'notification:read:own',
    description: 'Read own notifications',
    category: PermissionCategory.Notification,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'notification:update:own',
    description: 'Mark notifications as read',
    category: PermissionCategory.Notification,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'notification:delete:own',
    description: 'Delete own notifications',
    category: PermissionCategory.Notification,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'notification:preferences:update:own',
    description: 'Update notification preferences',
    category: PermissionCategory.Notification,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'notification:send:any',
    description: 'Send notifications to any user (system/admin)',
    category: PermissionCategory.Notification,
    requiresContext: false,
    isConditional: false,
  },

  // ===== ADMIN PERMISSIONS (14) =====
  {
    permission: 'admin:dashboard:access',
    description: 'Access admin dashboard',
    category: PermissionCategory.Admin,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'admin:metrics:view',
    description: 'View system metrics',
    category: PermissionCategory.Admin,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'admin:users:manage',
    description: 'Manage all users',
    category: PermissionCategory.Admin,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'admin:chamas:manage',
    description: 'Manage all chamas',
    category: PermissionCategory.Admin,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'admin:transactions:view',
    description: 'View all transactions',
    category: PermissionCategory.Admin,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'admin:apikeys:manage',
    description: 'Manage API keys',
    category: PermissionCategory.Admin,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'platform:settings:update',
    description: 'Update platform settings',
    category: PermissionCategory.Admin,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'platform:maintenance',
    description: 'Perform platform maintenance',
    category: PermissionCategory.Admin,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: 'admin:*',
    description: 'All admin permissions (wildcard)',
    category: PermissionCategory.Admin,
    requiresContext: false,
    isConditional: false,
  },
  {
    permission: '*',
    description: 'All system permissions (super admin wildcard)',
    category: PermissionCategory.Admin,
    requiresContext: false,
    isConditional: false,
  },
];
