apiVersion: 1

datasources:
  - name: Alertmanager
    type: alertmanager
    access: proxy
    orgId: 1
    url: http://alertmanager:9093
    basicAuth: false
    isDefault: false
    editable: false
    uid: alertmanager
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true