// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               v3.21.12
// source: auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export interface CreateUserRequest {
  phone: string;
  pin: string;
  npub: string;
  roles: string[];
}

export interface AuthUserRequest {
  Authentication: string;
}

export interface User {
  id: string;
  pin: string;
  /** Users phone number identifier */
  phone?: string | undefined;
  /** Users phone number has been verified via SMS */
  phoneVerified: boolean;
  /** Users nostr npub identifier */
  npub?: string | undefined;
  /** Users name or nym */
  name?: string | undefined;
  /** Users avatar url */
  avatarUrl?: string | undefined;
  /** Users roles */
  roles: string[];
}

export interface AuthServiceClient {
  createUser(request: CreateUserRequest): Observable<User>;

  authenticate(request: AuthUserRequest): Observable<User>;
}

export interface AuthServiceController {
  createUser(
    request: CreateUserRequest,
  ): Promise<User> | Observable<User> | User;

  authenticate(
    request: AuthUserRequest,
  ): Promise<User> | Observable<User> | User;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['createUser', 'authenticate'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('AuthService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('AuthService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const AUTH_SERVICE_NAME = 'AuthService';
